//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle.RightNow.Cti.MediaBar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oracle.RightNow.Cti.MediaBar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to login.
        /// </summary>
        public static string AgentLogin {
            get {
                return ResourceManager.GetString("AgentLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to logout.
        /// </summary>
        public static string AgentLogout {
            get {
                return ResourceManager.GetString("AgentLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANI / Call Status.
        /// </summary>
        public static string AniorCall {
            get {
                return ResourceManager.GetString("AniorCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.answer.png.
        /// </summary>
        public static string AnswerImageUri {
            get {
                return ResourceManager.GetString("AnswerImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string AnswerTooltip {
            get {
                return ResourceManager.GetString("AnswerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.conference.blind.png.
        /// </summary>
        public static string BlindConferenceImageUri {
            get {
                return ResourceManager.GetString("BlindConferenceImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.transferblind.png.
        /// </summary>
        public static string BlindTransferImageUri {
            get {
                return ResourceManager.GetString("BlindTransferImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.chat.png.
        /// </summary>
        public static string ChatImageUri {
            get {
                return ResourceManager.GetString("ChatImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string ChatTooltip {
            get {
                return ResourceManager.GetString("ChatTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.completeconference.png.
        /// </summary>
        public static string CompleteConferenceImageUri {
            get {
                return ResourceManager.GetString("CompleteConferenceImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete conference.
        /// </summary>
        public static string CompleteConferenceToolTip {
            get {
                return ResourceManager.GetString("CompleteConferenceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.completetransfer.png.
        /// </summary>
        public static string CompleteTransferImageUri {
            get {
                return ResourceManager.GetString("CompleteTransferImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete transfer.
        /// </summary>
        public static string CompleteTransferToolTip {
            get {
                return ResourceManager.GetString("CompleteTransferToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.conference.png.
        /// </summary>
        public static string ConferenceImageUri {
            get {
                return ResourceManager.GetString("ConferenceImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blind Conference the call.
        /// </summary>
        public static string ConferenceToolTip {
            get {
                return ResourceManager.GetString("ConferenceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consult conference the call.
        /// </summary>
        public static string ConsultConferenceToolTip {
            get {
                return ResourceManager.GetString("ConsultConferenceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consult transfer the call.
        /// </summary>
        public static string ConsultTransferToolTip {
            get {
                return ResourceManager.GetString("ConsultTransferToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.hangup.png.
        /// </summary>
        public static string HangupImageUri {
            get {
                return ResourceManager.GetString("HangupImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hang up.
        /// </summary>
        public static string HangupTooltip {
            get {
                return ResourceManager.GetString("HangupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.hold.png.
        /// </summary>
        public static string HoldImageUri {
            get {
                return ResourceManager.GetString("HoldImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place the interaction on hold.
        /// </summary>
        public static string HoldTooltip {
            get {
                return ResourceManager.GetString("HoldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.incident.png.
        /// </summary>
        public static string IncidentImageUri {
            get {
                return ResourceManager.GetString("IncidentImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident.
        /// </summary>
        public static string IncidentTooltip {
            get {
                return ResourceManager.GetString("IncidentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Conferenced.
        /// </summary>
        public static string InteractionConferenced {
            get {
                return ResourceManager.GetString("InteractionConferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Consulting.
        /// </summary>
        public static string InteractionConsulting {
            get {
                return ResourceManager.GetString("InteractionConsulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string InteractionStateActive {
            get {
                return ResourceManager.GetString("InteractionStateActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting Chat.
        /// </summary>
        public static string InteractionStateChat {
            get {
                return ResourceManager.GetString("InteractionStateChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialing.
        /// </summary>
        public static string InteractionStateDialing {
            get {
                return ResourceManager.GetString("InteractionStateDialing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string InteractionStateDisconnected {
            get {
                return ResourceManager.GetString("InteractionStateDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On hold.
        /// </summary>
        public static string InteractionStateHeld {
            get {
                return ResourceManager.GetString("InteractionStateHeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting Incident.
        /// </summary>
        public static string InteractionStateIncident {
            get {
                return ResourceManager.GetString("InteractionStateIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringing.
        /// </summary>
        public static string InteractionStateRinging {
            get {
                return ResourceManager.GetString("InteractionStateRinging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string MediaTypeChat {
            get {
                return ResourceManager.GetString("MediaTypeChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.chat.png.
        /// </summary>
        public static string MediaTypeChatImageUri {
            get {
                return ResourceManager.GetString("MediaTypeChatImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string MediaTypeEmail {
            get {
                return ResourceManager.GetString("MediaTypeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.mediatype.email.png.
        /// </summary>
        public static string MediaTypeEmailImageUri {
            get {
                return ResourceManager.GetString("MediaTypeEmailImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident.
        /// </summary>
        public static string MediaTypeIncident {
            get {
                return ResourceManager.GetString("MediaTypeIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.incident.png.
        /// </summary>
        public static string MediaTypeIncidentImageUri {
            get {
                return ResourceManager.GetString("MediaTypeIncidentImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string MediaTypeUnknown {
            get {
                return ResourceManager.GetString("MediaTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice.
        /// </summary>
        public static string MediaTypeVoice {
            get {
                return ResourceManager.GetString("MediaTypeVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.mediatype.voice.png.
        /// </summary>
        public static string MediaTypeVoiceImageUri {
            get {
                return ResourceManager.GetString("MediaTypeVoiceImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web incident.
        /// </summary>
        public static string MediaTypeWeb {
            get {
                return ResourceManager.GetString("MediaTypeWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.mediatype.web.png.
        /// </summary>
        public static string MediaTypeWebImageUri {
            get {
                return ResourceManager.GetString("MediaTypeWebImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no active interaction.
        /// </summary>
        public static string NoInteractionTimer {
            get {
                return ResourceManager.GetString("NoInteractionTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parties in Conference : .
        /// </summary>
        public static string PartiesConference {
            get {
                return ResourceManager.GetString("PartiesConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.retrieve.png.
        /// </summary>
        public static string RetrieveImageUri {
            get {
                return ResourceManager.GetString("RetrieveImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve the interation.
        /// </summary>
        public static string RetriveTooltip {
            get {
                return ResourceManager.GetString("RetriveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Oracle.RightNow.Cti.Mediabar;component/Images/mediabar.voice.transfer.png.
        /// </summary>
        public static string TransferImageUri {
            get {
                return ResourceManager.GetString("TransferImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blind transfer the call.
        /// </summary>
        public static string TransferToolTip {
            get {
                return ResourceManager.GetString("TransferToolTip", resourceCulture);
            }
        }
    }
}
